// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kktnwrptrtldvkvxlshd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrdG53cnB0cnRsZHZrdnhsc2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTY5ODEsImV4cCI6MjA3MDQ5Mjk4MX0.fw7jrOldHU5QxnbFApeDvKU1Xcs2gI70SS3ZQ69az5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});